version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-carona
    environment:
      MYSQL_DATABASE: backendFateCarona
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s

  dbMongo:
    image: mongo:6
    container_name: mongo-carona
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend_java:
    build: ./fatecCarCarona
    container_name: backend-carona
    depends_on:
      db:
        condition: service_healthy
      dbMongo:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/backendFateCarona
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - MONGO_URI=mongodb://dbMongo:27017/backendfateccarona

volumes:
  mysql_data:
  mongo_data:
