spring.application.name=fatecCarCarona





spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/backendFateCarona
##spring.datasource.url=jdbc:mysql://localhost:3306/backendfatecCarona

spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
hibernate.dialect=org.hibernate.spatial.dialect.MySQL8SpatialDialect
api.security.token.secret = my-secret-key-from-video

#Mongo
spring.data.mongodb.uri=mongodb://localhost:27017/backendfateccarona


